version: "3.9"

services: 
  # Ruby on Rails5
  web:
    container_name: rails5-web
    # image: ruby:$RUBY_TAG
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=$USERNAME
        - UID=$UID
        - RUBY_TAG=$RUBY_TAG
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/$USERNAME/certs/letsencrypt/live/example.com/fullchain.pem:/etc/nginx/certs/example.com.crt
      - /home/$USERNAME/certs/letsencrypt/live/example.com/privkey.pem:/etc/nginx/certs/example.com.key
      - .:/myapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - VIRTUAL_HOST=rails5.example.com
      # - VIRTUAL_PORT=80
      # - VIRTUAL_PORT=433
      - VIRTUAL_PORT=3000
      - CERT_NAME=example.com
    expose:
      - "80"
      - "433"
    depends_on:
      - db
    networks: 
      - proxy_default

  # Postgresql
  db:
    container_name: rails5-db
    image: postgres:$POSTGRE_TAG
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    networks: 
      - proxy_default

networks:
  proxy_default:
    external: true
